### ISSUE TITLE
Organiser les scripts

### ISSUE THREAD

**Issue by GuillaumeDesforges** [KIClubinfo/upont-v4#48]
https://github.com/KIClubinfo/upont-v4/blob/f4048720a0c6fb528d4da5e1abeb68a63aa3edc4/build.sh#L1

Il y a des scripts bash un peu partout.
C'est ok, mais pas top.

Vous pouvez utiliser un outil pour gérer vos tâches.

Pour le moment, vu que vous avez des commandes simples, vous pouvez faire un Makefile, qui permet de configurer des taches pour l'outil `make`, e.g.

`./Makefile`
```makefile
build:
    docker-compose build ...
run:
    docker-compose up ...
```

Une autre option simple est de les mettre dans un dossier `./scripts`

**Comment by bastienlc** [comment]
Fixed by #60.
