### ISSUE TITLE
Utiliser un seul Dockerfile

### ISSUE THREAD

**Issue by GuillaumeDesforges** [KIClubinfo/upont-v4#49]
Vous utilisez deux Dockerfile différents

https://github.com/KIClubinfo/upont-v4/blob/f4048720a0c6fb528d4da5e1abeb68a63aa3edc4/back/Dockerfile#L1

https://github.com/KIClubinfo/upont-v4/blob/f4048720a0c6fb528d4da5e1abeb68a63aa3edc4/back/Dockerfile_prod#L1

Un des bénéfices de l'utilisation de Docker est d'assurer d'avoir la reproductibilité entre votre environnement de test et votre environnement de prod.

En utilisant deux dockerfiles test/prod, vous perdez ce bénéfice.

**Comment by bastienlc** [comment]
Fixed by #62.
