### ISSUE TITLE
Documenter les variables d'environnement

### ISSUE THREAD

**Issue by GuillaumeDesforges** [KIClubinfo/upont-v4#50]
https://github.com/KIClubinfo/upont-v4/blob/f4048720a0c6fb528d4da5e1abeb68a63aa3edc4/back/gunicorn.conf.py#L5

Les variables d'env sont une plaie à gérer dans un projet, il est bénéfique de maintenir même une simple liste dans un README.

Exemple

| Env var | Description | Dev | Prod |
| -------- | -------------|----- | ------|
| GUNICORN_NB_WORKERS | Nombre de workers pour le WSGI gunicorn |  | X |

```markdown
| Env var | Description | Dev | Prod |
| -------- | -------------|----- | ------|
| GUNICORN_NB_WORKERS | Nombre de workers pour le WSGI gunicorn |  | X |
```

**Comment by bastienlc** [comment]
Fixed by #61.
