### ISSUE TITLE
Les tests sont lancés au démarrage en prod

### ISSUE THREAD

**Issue by GuillaumeDesforges** [KIClubinfo/upont-v4#51]
https://github.com/KIClubinfo/upont-v4/blob/f4048720a0c6fb528d4da5e1abeb68a63aa3edc4/back/entrypoint.prod.sh#L14

Les tests sont lancés au démarrage en prod.

Je crois que le bash n'est pas lancé avec le flag `-e`, donc si les tests ratent ça ne devrait pas arrêter le script (vous aurez juste les erreurs dans les logs, mais ça lancera quand même.

De plus, si votre but est de faire crash le serveur au démarrage si les tests ratent, alors:

* cela va vous compliquer la vie
* vous configurer le back pour restart dans docker-compose
  https://github.com/KIClubinfo/upont-v4/blob/f4048720a0c6fb528d4da5e1abeb68a63aa3edc4/docker-compose_prod.yml#L27
  Donc ça va spam en boucle si ça fail 

Une alternative est de mettre en place une CI sur votre repo GitHub avec GitHub Actions.

**Comment by bastienlc** [comment]
Fixed by #59.
