### ISSUE TITLE
Mieux lock les dépendances 

### ISSUE THREAD

**Issue by GuillaumeDesforges** [KIClubinfo/upont-v4#53]
Disclaimer, la gestion des dépendances en Python est un calvaire.

Vous pensez aujourd'hui que mettre `<package>==<version>` permet de freeze vos dépendences?

🙂

Chacun de vos packages dans `requirements.txt` installe probablement d'autres dépendances, qui ne sont généralement pas freeze.

Ceci peut vous jouer des tours à long terme car chaque `pip install -r requirements.txt` peut installer des versions différentes depuis PyPI au fur et à mesure que le temps passe.

Plusieurs solutions de premier order:

- Utiliser `poetry`: https://python-poetry.org/docs/
- Faire un lockfile manuel en utilisant `pip freeze > requirements-freeze.txt`,  qui devient le fichier vous utilisez pour déployer en prod.
  Cette méthode est assez manuelle et il faut bien comprendre comment/pourquoi ça marche. Bref, je ne recommande pas.

**Comment by bastienlc** [comment]
Fixed by #62.
